ABILITY_DATA = {
  :ARCANEFINALE     => { :desc => proc { _INTL("Turns to Finale Form when only unfainted on team. Ignores the condition of a perfect battle.") }, },
  :ADRENALINERUSH   => { :desc => proc { _INTL("Raises Speed by four steps when its HP is lowered below half. Moves next when being hit.") }, },
  :CASHFLOW         => { :desc => proc { _INTL("Consumes coins to heal for 1/10th the amount consumed when its HP becomes half or less. This can overheal.") }, },
  :CHEEKPOUCH       => { :desc => proc { _INTL("When this Pokémon eats a Berry, it restores 25% of its max health.") }, },
  :CHILLINGNEIGH    => { :desc => proc { _INTL("Raises Attack by 2 steps after knocking out any Pokémon.") }, },
  :DARKSCALECLOUD   => { :desc => proc { _INTL("Upon entry, spreads poisonous dust which poisons any Pokémon stay in for 2 turns. When any Pokémon are poisoned, boosts Defense by 2 steps.") }, },
  :DEFEATIST        => { :desc => proc { _INTL("Halves move damage when HP is greater than 50%.") }, },
  :DISCOLIGHTS      => { :desc => proc { _INTL("It changes secondary type to that of the dance moves it's about to use.") }, },
  :DRYSKIN          => { :desc => proc { _INTL("Heals 1/8th HP in rainstorm, 1/4th when hit by Water-type moves.") }, },
  :EMOTIONAURA      => { :desc => proc { _INTL("Upon entry, creates an Emotion Room for 4 turns, adding an ability every turn.") }, },
  :EXTRASCOOP       => { :desc => proc { _INTL("Upon entry, this Pokémon heals itself for 1/5th max HP. This can overheal.") }, },
  :FINESUGAR        => { :desc => proc { _INTL("Heals 1/8th HP in sunshine, 1/4th when hit by Fire-type moves.") }, },
  :GRIMNEIGH        => { :desc => proc { _INTL("Raises Sp. Atk by 2 steps after knocking out any Pokémon.") }, },
  :HEROICFINALE     => { :desc => proc { _INTL("Turns to Finale Form when only unfainted on team. Ignores the condition of a perfect battle.") }, },
  :HUBRIS           => { :desc => proc { _INTL("Raises Sp. Atk by 2 steps after knocking out any Pokémon.") }, },
  :IGNITIONCYCLE    => { :desc => proc { _INTL("Each turn, raises Speed by 4 steps and loses 1/8th max HP. If Speed was maxed, instead Speed and HP are reset.") }, },
  :ILLUSION         => { :desc => proc { _INTL("Comes out disguised as a Pokémon in back. Reduces damage by 30% in disguise.") }, },
  :IMPERIOUS        => { :desc => proc { _INTL("Raises Speed by four steps when a stat is lowered by a foe. Makes foes unable to use priority moves.") }, },
  :JOYOUSSORROW     => { :desc => proc { _INTL("Uses Wish when hit by an attack or knocks out any Pokémon.") }, },
  :KILLJOY          => { :desc => proc { _INTL("Pokémon can't raise their stats. Pokémon that use dance or sound moves take damage equal to 1/4th their HP.") }, },
  :MOXIE            => { :desc => proc { _INTL("Raises Attack by 2 steps after knocking out any Pokémon.") }, },
  :NATURALCURE      => { :desc => proc { _INTL("Heals all non-volatile status conditions and 10% of max HP when it switches out.") }, },
  :OVERCHARGE       => { :desc => proc { _INTL("After knocking out any Pokémon/being knocked out, raises/lowers its/attacker's Sp. Atk and Speed by 2 steps.") }, },
  :PERENNIALPAYLOAD => { :desc => proc { _INTL("After fainting from exploding, revives after five turns, but requires above 50% HP if caused by others.") }, },
  :PLURIPOTENCE     => { :desc => proc { _INTL("Copies opponents' species' legal Abilities.") }, },
  :PRESSURE         => { :desc => proc { _INTL("This Pokémon raises the foe's PP usage. Upon entry, resets foe's positive stat steps.") }, },
  :REFRACTIVE       => { :desc => proc { _INTL("It changes secondary type to that of the light moves it's about to use.") }, },
  :RUSTWRACK        => { :desc => proc { _INTL("The Pokémon is also Steel-type.") }, },
  :SHIFTINGFIST     => { :desc => proc { _INTL("It changes secondary type to that of the punching moves it's about to use.") }, },
  :SPEEDBOOST       => { :desc => proc { _INTL("Speed is raised by 1 step at the end of each of its turns.") }, },
  :SPINTENSITY      => { :desc => proc { _INTL("Speed is raised each turn. Speed is reset when hit, but the attacker takes 1/8th HP damage for each step lost, this Pokémon takes 1/16th.") }, },
  :STUBBORN         => { :desc => proc { _INTL("Prevents its stats from being lowered by more than 1 step at a time. Pokémon that do this take damage equal to 1/4th their HP.") }, },
  :SUMMERSZENITH    => { :desc => proc { _INTL("Summons sunshine for four turns when hit by an attack or knocks out any Pokémon.") }, },
  :SWIFTSTOMPS      => { :desc => proc { _INTL("The user's Speed is doubled while using kicking moves. Every third kicking hit must be a crit.") }, },
  :THUNDERSTORM     => { :desc => proc { _INTL("Charges after using every 2 damaging moves in sandstorm, doubling the power of its next Electric-type move.") }, },
  :TOILANDTROUBLE   => { :desc => proc { _INTL("Foes suffer 50% more move damage reduction from burn, frostbite, numb, and poison.") }, },
  :TOXINTAX         => { :desc => proc { _INTL("Heals this Pokémon by 1.5x the damage other battlers take from being poisoned.") }, },
  :UNFAZED          => { :desc => proc { _INTL("Takes 20% less damage if the move is more than normal-effective.") }, },
  :UNIDENTIFIED     => { :desc => proc { _INTL("This Pokémon is Mutant-type. If it is Deoxys, it will have multiple movesets.") }, },
  :VERDANT          => { :desc => proc { _INTL("Powers up Grass-type moves of itself and its allies by 30%.") }, },
  :WELLEQUIPPED     => { :desc => proc { _INTL("Can hold two items.") }, },
}.freeze