module Settings
  NUM_STORAGE_BOXES = 200

  POISON_IN_FIELD             = false
  TAUGHT_MACHINES_KEEP_OLD_PP = true
  FAINTED_POKEMON_EARN_EXP    = false
  SEND_PC_HEALING             = false

  # Button used for Text Skipping (Default = :X)
  TEXT_SKIP_KEY = :V

  # Button used for Fast Forward (Default = :F)
  FAST_FORWARD_KEY = :Q

  CURSE_STATUS_DOUBLED_RATE = 1.0

  REST_HEALING_AMT     = 5
  SWITCH_HEALING_AMT   = 10

  STEP_RECOVERY_TURN        = 4
  NATURAL_HEALING_TURN      = 5
  FAINT_HEALING_TURN        = 12
  FAINT_HEALING_TURN_DOULBE = 6

  BATTLE_ENDING_AMT  = 50
  BATTLE_ENDING_PLUS = 70

  ROWE_STAB_OFF           = 5
  ROWE_STAB_OFF_MONO      = 10
  ROWE_STAB_DEF           = 5
  ROWE_STAB_DEF_MONO      = 10

  GLOBAL_SUPREME_OVERLORD = 5
  REVENGE_MECHANICS       = 5
  REVENGE_MECHANICS_PLUS  = 25
  BIGGER_SIDE_PUNISHMENT  = 5

  KILL_PUNNISHMENT = 70

  EXP_RATE_BOOST   = 4.5
  MONEY_RATE_BOOST = 2.5
  CATCH_RATE_BOOST = 3

  PARTY_MOST_TYPE_BONUS_THRESHOLD = 4

  ITEM_CLAUSE          = false
  STATUS_CLAUSE        = true
  PKMN_REVIVAL         = true
  STEP_RECOVERY        = true
  BATTLE_NO_MONEY_LOSS = true
  COPY_PLAYER_TRIBE    = false
  AI_PREDICT           = true

  DEFAULT_ITEMS = %i[SITRUSBERRY]
  UNRECOVERABLE = %i[LEPPABERRY]
end