name: Restart Cable Club (Live)

on:
    workflow_dispatch:

jobs:
    restart:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Restart live server
              run: .\deploy_cableclub.ps1 -Live -RestartOnly
              shell: pwsh
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
